name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'
    - name: Build
      run: xcodebuild -scheme navigation-flow build -destination "platform=iOS Simulator,name=iPhone 17 Pro Max,OS=latest" -derivedDataPath .build
    - name: Run tests
      run: xcodebuild -scheme navigation-flow test -destination "platform=iOS Simulator,name=iPhone 17 Pro Max,OS=latest" -derivedDataPath .build -enableCodeCoverage YES
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        xcode: true
        xcode_archive_path: ${{ env.RESULT_BUNDLE_PATH }}
